version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    ports:
      - "8000:8000"
    build:
      context: ./api
      dockerfile: Dockerfile

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
